### ISSUE TITLE
Primitive Mobs Harpies not being blocked by Mega Torch (Mod Compatibility)

### ISSUE THREAD

**Issue by nightstick24** [Xalcon/TorchMaster#124]
Hey there, love the mod to death, I added it to the 1.12.2 Mod Pack, MC Eternal, and I noticed that the Mega Torches don't stop the Harpies from the Primitive Mobs mod from spawning. They seem to stop all the other hostile mobs, just not Harpies. I also tried the Dread Lamp to see if that'd get it but no luck with that either.

I tried adding primitivemobs:harpy - which works in the /kill command - into the blacklist for the Mega Torch, but after restarting Minceraft they're still spawing. Not sure what the issue is, it could totally be user error, but if you've got any ideas on fixing it I'd be greatful for some help!

Here's the entity dump, if that's helpful at all. https://pastebin.com/fWFk32b7

**EDIT: In TorchMaster's options there's a setting for more aggressive spawn blocking. I tried setting that to true after seeing someone else mention it and that's stopped the Harpies from spawning,**

Thanks for the amazingly useful mod!

**Comment by Xalcon** [comment]
Looks like some other mod (maybe primitivemobs itself, i dont know) explicitly sets the CheckSpawn event result to `allow`. The default behavior of Torchmaster is to check the current CheckSpawn result (which should be `default`). If its `Allow`, torchmaster will skip any torch checks and just allow the spawn (since some other mod explicitly requested it). The Aggressive Spawn Blocking setting will override this behavior and do the torch checks anyway.

It's good to know this setting is actually useful in some mod setups. Thanks for the headsup. I do not consider this to be a bug then. If anyone disagrees, feel free to comment :)
