### ISSUE TITLE
Removing Feral Flare Doesn´t Remove Light Points

### ISSUE THREAD

**Issue by ghost** [Xalcon/TorchMaster#172]
I'm using the beta 2 in 1.18.1 and the lights aren´t being removed after I remove the Feral Lantern.
https://ibb.co/Y8ZQCtb
I even used the item to remove the lights.

**Comment by Xalcon** [comment]
I've been looking into this problem, but I'm unsure what is going on.
Generally, this bug occurs after the tile entity has unloaded (i.e. due to a world restart or just chunk unload) - the `BlockEntity::save()` method is not called. I am making sure I call `BlockEntity::setChanged()` after placing a light block, but for some reason `save` isnt called during a chunk save.

I'll be looking into this when I find more time but if someone else has an idea, hit me up.

**Comment by Xalcon** [comment]
As always, fixing things a few minutes later x) (Thanks to mcjty's wiki)
Switched to `saveAdditional()` and it's working now, please try version 18.0.3-beta either from the torchmaster github releases or from minecraftforge (once approved by curseforge)
