### ISSUE TITLE
Feral Flare Lantern & The Frozen Pearl block.

### ISSUE THREAD

**Issue by HeavyDeception** [Xalcon/TorchMaster#198]
This is just an Idea but would it be possible to have a block that with a GUI to set a radius or area stopping the F.F.Lantern from lighting that area up?

**Comment by Xalcon** [comment]
Its a planned feature, but due to time constraints, I'm unable to work on the mod for everything but a simple update at the moment.
The feature will be limited to line-of-sight (no special handling for ransparent blocks like glass). Everything else is too much out of scope

https://github.com/Xalcon/TorchMaster/issues/174
