### ISSUE TITLE
[1.20.1] Dread Lamp blocks the use of spawn eggs

### ISSUE THREAD

**Issue by JaisDK** [Xalcon/TorchMaster#214]
While having a dread lamp it's not possible to spawn in anything with a spawn egg, not even passive mobs despite `blockOnlyNaturalSpawns` being set to true.

Looking through your code I can see that `blockOnlyNaturalSpawns` only allows spawner spawn, not actually all non-natural spawns as the config name suggests.

I have a mod which relies on being able to use spawn eggs and this mod causes big losses for the players when they try to spawn the mob they crafted. I suggest you allow a few more spawn types when `blockOnlyNaturalSpawns` is true namely `BREEDING`, `SPAWN_EGG`, `BUCKET` and `DISPENSER`

**Comment by Xalcon** [comment]
Ah yes, I think that's a more recent change in Minecraft. I'll look into it and provide a fix soon

**Comment by Xalcon** [comment]
Fixed in
* v20.1.2 for MC 1.20.1
* v19.4.2 for MC 1.19.4
* v19.2.92 for MC 1.19.2

I've introduced the concept of intentional spawns which includes the following:
https://github.com/Xalcon/TorchMaster/blob/e1fa888c31f1b8203053f94fc4a388bf2a9654b7/src/main/java/net/xalcon/torchmaster/common/logic/entityblocking/EntityBlockingEventHandler.java#L29-L35
These will never be blocked
