### ISSUE TITLE
Updating Torchmaster causing Megatorch/Dread Lamp to not work

### ISSUE THREAD

**Issue by Pa-nts** [Xalcon/TorchMaster#216]
When updating the mod from 20.1.1 to 20.1.2 if done on a world generated with 20.1.1 installed and later updated, neither the mega torch nor the dread lantern seem to be working.

Mobs are seen below spawning at a distance from the lantern.
![2023-07-28_14 16 46](https://github.com/Xalcon/TorchMaster/assets/27230489/f60a1d5d-eca7-4150-bb43-b5e90d92579c)

Then once you've updated the mod on the same world they are seen spawning within the targeted area.
![2023-07-28_14 20 49](https://github.com/Xalcon/TorchMaster/assets/27230489/e8e11cb8-e17e-4544-ab89-6b164daf25b1)

Steps to reproduce:

-    Create Minecraft world with Torchmaster version 20.1.1 installed

-    Once created place a mega torch then close Minecraft

-    Update the mod

-    Reopen Minecraft and select the previous world and mobs will spawn within the bounding box of the lamp/torch

**Comment by Xalcon** [comment]
jep, looks like I messed up. Single character typo in my code is causing this. I'll release a fix shortly

**Comment by Xalcon** [comment]
I've released version 20.1.3, 19.4.3 and 19.2.93
They are available via Modrinth and the [Github Releases Page](https://github.com/Xalcon/TorchMaster/releases) - unfortunately, I can't upload anything to curseforge at the moment because their malware detection is flagging all of my uploads for manual review (and it looks like I'm not the only one affected by this).

**Comment by Xalcon** [comment]
New versions are now also available on curseforge.
