### ISSUE TITLE
InControl compatibility issues

### ISSUE THREAD

**Issue by kwpugh** [Xalcon/TorchMaster#52]
Hi,

Does the mega torch block spawns by using light level or some other means?

I’m using InControl and have a spawn rule that allows hostiles to spawn if light level is below 8.   The mega torch has a visual light range of 16x16 blocks and mobs spawn right outside that range.

Thanks

**Comment by paulstelian97** [comment]
I think it blocks spawn events themselves.

**Comment by Xalcon** [comment]
I'll close this for now. Please comment on this issue if this problem still exists.

**Comment by TheCommonCard** [comment]
Possible solution:
NOTE: minecraft version is unspecified in original post. results will work for versions 1.18.x and 1.19.x

EDIT: Using Configured, opening the config for Torchmaster and setting "Aggressive Spawn Checks" to true might solve the issue with the mega torch

you could also go to "Mega Torch Entity Block List Overrides" and add in it's own entry this text (with quotes):

"+minecraft:zombie"

Have the OP check their config (if this issue is still relevant to them)
make sure somewhere in their conditions in "spawner.json" the following line of text is inserted:

"maxlight_full": 7

on top of that, make sure in "spawn.json" the following couple of lines are present (you can add more, these are just required)

"hostile": "true",
"result": "default"

note that "allow" will ALWAYS accept spawns regardless of any conditions, and "deny" will ALWAYS reject spawns.
"default" keeps all other non-specifically defined traits of mob spawning the same (which means the mega torch SHOULD work properly)

**Comment by pantsguyapp** [comment]
I put maxlight_full as one of the conditions in spawner.json and the game said it is an invalid condition. I was in 1.19.2
