### ISSUE TITLE
Question about burn-out rate

### ISSUE THREAD

**Issue by Ash70** [Xalcon/TorchMaster#58]
I'm not getting it right somehow. I want the mega torch to burn out over a period of 96 MC days.
To this end I set:

`I:MegaTorchBurnoutRate=2304000`   (96 * 24000 ticks)

and I keep:

`I:MegaTorchBurnoutValue=1`

Is this correct? For some reason the torch keeps burning after the set time (I checked with different values obviously as a 96 MC day waiting-period is no fun)

**Comment by Xalcon** [comment]
You have your values mixed up. The `I:MegaTorchBurnoutValue` defines the "health" of a torch whereas the `I:MegaTorchBurnoutRate` defines how much of this "health" is removed per tick.

I think i will change the config around to make this more reasonable. I didnt realise that there is no point in having the burnout rate configurable. I will convert this field into a boolean, since thats what it actually is.
