### ISSUE TITLE
[1.6.3] Megatorch not working in custom dimension

### ISSUE THREAD

**Issue by Shandoo94** [Xalcon/TorchMaster#61]
I have my base in a RFTools void-dimension. Placing am megatorch there does not prevent the spawning of hostile mobs. The torch seems to function normal in the overworld.

**Comment by Xalcon** [comment]
i've just tested this, using the following versions and i'm unable to reproduce the issue.
* mcjtylib-1.12-2.6.7
* rftools-1.12-7.33
* rftoolsdim-1.12-5.53
* MC Forge 14.23.3.2655
* Torchmaster 1.6.3

I've created a simple void dimensions, put down 2 layers of stone to create a spawning pad for hostile mobs. Just a few seconds after creating the spawning pads, I saw mobs spawning. I then placed down a mega torch and killed all mobs by switching the difficulty to peaceful and then back to normal. No further spawns occured. I then proceeded  by removing the mega torch again, which caused mobs to spawn as expected. Can you verify this issue with the latest version of each mod with no other mods installed?

**Comment by Xalcon** [comment]
looks like forge removed a feature that was intended to be removed in 1.13. I'm working on a fix.

**Comment by Xalcon** [comment]
I've pushed a fix to this repo. Its not ready for release yet since I need to do some more testing and add some backwards compatibility code - otherwise everyone using the mod will need to pickup and replace all torches and lamps. In general, the storage logic should be much cleaner now as its realized as dimension specific world capabilities.

I'll add the backwards compat code later today and push an update to curseforge this evening.
