### ISSUE TITLE
Light Passing Through Walls & Floors

### ISSUE THREAD

**Issue by x1xHEADSHOTSx1x** [Xalcon/TorchMaster#71]
I am playing on the Stoneblock mod pack version 1.0.17 and the found the Feral Flare Lantern and fell in love with it as it similar to the Thaumcraft Arcane Lamp in how it works. I did find a bug in the function of it. The lantern removes dark spaces through walls and floors. I first found this out when my darkroom stopped working, it is about 15-18 blocks away from the nearest lantern. The pack is using torchmaster-1.12.2-1.6.4.62.jar. If you like a back up of my world for testing let me know. Enjoying your work keep it coming.

Thanks,
x1xHEADSHOTSx1x

**Comment by Xalcon** [comment]
This is actually intended. I might add an option to take line of sight into account though.

**Comment by x1xHEADSHOTSx1x** [comment]
What about a shift-clickable setting to adjust the range or the function of the lantern. Also, wouldn't adjusting this function make it more server friendly as the lantern would not be trying to do lighting updates everytime a block is placed? Especially if the block is placed for example 15 blocks down through 5 layers of stone.

**Comment by Xalcon** [comment]
A range limiter wouldnt really make it more efficient due to the way the lantern works. It simply adds an invisible light block at a random position in its range. It doesnt matter how big this range is. Also, light updates will always happen when you place a block - the lantern itself has nothing to do with it.
Dont get me wrong, placing lights can be pretty taxing for servers, but since the lantern wont place a light if the light level is high enough, it will eventually saturate itself.

Even though I think the lantern is pretty efficient, I'll consider adding a few more configuration options to it.

**Comment by Xalcon** [comment]
A Line of sight feature has been added as a Gui option to the feral flare lantern. By default the lantern will ignore line of sight but it can be enabled on a lantern to lantern basis.

This will be part of the next release after i've tested the mod thoroughly.
