### ISSUE TITLE
[Suggestion] add cave lighter

### ISSUE THREAD

**Issue by Trinsdar** [Xalcon/TorchMaster#79]
It would be nice to be able to light up the caves in an area.

**Comment by Xalcon** [comment]
While a nice suggestion, i'm a bit unsure how to solve this technically. As far as I know, there is nothing that tells me if something is a cave in minecraft. 

I have several ideas, one cooler but harder to implement than the other but I will play around with some of the ideas I have. An upgrade for the terrain lighter that doesnt just light up the highest blocks but can also goes underground might be an option. 

There is one thing though: a cave lighter might have a serious impact on game difficulty, since you plug down a bunch of them, light up everthing and go inside once everything is save. At which stage of the game do you think you would use this? I assume this is more of an early to midgame block. What ingredents would you use to craft it? Just collecting some ideas on how to balance this properly.

**Comment by Trinsdar** [comment]
It would probably be more mid game and for recipes maybe it can be locked behind the end or nether if the end is too late game

**Comment by scribbler957** [comment]
It's not really the lighting that's the issue. The Mega Torch will stop spawning around it and you can go in light up and move the torch. For that matter, you could run in as far as you dare, spamming torches, run 128 blocks away to force those areas to clear out, and repeat. It's really about how easy it becomes. That and whether it's about spawning or light. The Astral Sorcery cave illuminator isn't particularly expensive or hard to make and the rarer ingredients may already be in the chests of your local astral shrine. It also has a seemingly enormous range.
Maybe a machine that slowly consumes a mega torch to light up the area the mega torch would affect? Power it with glowstone so it uses one piece every time it places a light?

**Comment by Xalcon** [comment]
> you could run in as far as you dare, spamming torches, run 128 blocks away to force those areas to clear out, and repeat.

I never thought about suicide lighting a cave, that's a funny idea, lol.

>Maybe a machine that slowly consumes a mega torch to light up the area the mega torch would affect? Power it with glowstone so it uses one piece every time it places a light?

So, you think it would be a good idea to gate the cave lighter behind having a mega torch? I can get behind that. Adding the torch as part of the recipe and require a glowing resource like glowstone to work.

**Comment by ghost** [comment]
Well... in newer MC, they have addet an CaveAir-Block...
With this, this Funktion should be an peace of cake.... right? ^^;

**Comment by Shadowex3** [comment]
> 
> 
> > you could run in as far as you dare, spamming torches, run 128 blocks away to force those areas to clear out, and repeat.
> 
> I never thought about suicide lighting a cave, that's a funny idea, lol.
> 
> > Maybe a machine that slowly consumes a mega torch to light up the area the mega torch would affect? Power it with glowstone so it uses one piece every time it places a light?
> 
> So, you think it would be a good idea to gate the cave lighter behind having a mega torch? I can get behind that. Adding the torch as part of the recipe and require a glowing resource like glowstone to work. This would mean you need at least a few diamonds, a bunch of gold and a trip to the nether.


Another way to keep it from being too broken would be to require more effort on the part of the player. If people need to lay down an unbroken line of resource, redstone style, then they'll have to actually take the time to build a real mineshaft and account for how they descend.

_That_ would probably be some serious feature creep though, and is getting well into the territory of a full on gameplay mod.

**Comment by Xalcon** [comment]
Considering the scope of the mod, I'll close this for now. Even the Terrain Lighter was severely broken (in terms of balancing) and even that thing was only implemented because of mobs spawning at light level 7 and below. Ever since they changed this to 0, its much easier to light up your area. Also, the Mega Torch is already reasonably cheap to build. Adding something like the cave lighter would require balance changes to the mega torch, which I'm currently not willing to do. Lets keep the Mod simple.
