### ISSUE TITLE
Feral Flare Lantern blocking a ritual from Astral Sorcery

### ISSUE THREAD

**Issue by D1amxnd** [Xalcon/TorchMaster#85]
So as the Title says, after almost freaking out, I found out that my feral flare lantern blocked my ritual from Astral Sorcery. I am not sure where to report it, so I am doing it on both ends

**Comment by Xalcon** [comment]
Sadly, there is no way for me to fix this. I cant know if I'm allowed to place a light at a certain location. Other mods, that provide similar features (like Thaumcraft) will encounter the same issue.

In my opinion, this is a bug in astral sorcery since my light blocks mimic air blocks. I've added an comment to the issue on their side. https://github.com/HellFirePvP/AstralSorcery/issues/986

At the moment, this is impossible for me to fix.

**Comment by Xalcon** [comment]
Looks like the developers on AstralSorcery's side are not willing to fix this as it is intended behavior. I guess you are not supposed to light up astral sorcery's rituals.

I'll take a closer look at their source - maybe I can find a workaround for this. If someone else has anything helpful to contribute, I'm happy to hear it.  I really dislike it when mod authors cause incompatibilities like this :/ Sorry for your inconvenience.

**Comment by D1amxnd** [comment]
Ok thank you for replying to this, it took me ages to figure out that it was coming from your mod. I really enjoy playing with your mod and especially with the feral flare lantern, so this was a big bummer to me.

**Comment by D1amxnd** [comment]
I also understand that there is not a block supposed to be on the ritual but since these are no "real" blocks, they should be allowed on the ritual imo

**Comment by Xalcon** [comment]
I totally agree with you, but this is something that astral sorcery has to change - especially since other mods are affected as well. The Thaumcraft lamp (the Feral Flare Lantern is pretty much a copy of the thaumcraft lamp) will have the same issues - just like any other mod that has invisible pseudo-air blocks. Even worse: some mods place completly hidden blocks that players cannot control at all (railcraft was doing that in the past, not sure if they still do, but I'll check), effectivly breaking rituals by just walking through them.
