### ISSUE TITLE
[Suggestion] Allow certain mods to override spawing rules

### ISSUE THREAD

**Issue by katubug** [Xalcon/TorchMaster#88]
Firstly, thank you for the great mod! I appreciate how many configurable options there are.

Secondly, I recently added InfernalMobs to my pack, and I was hoping for some option in either config to allow them to spawn even in areas protected by the megatorch - the idea being that these creatures are powerful enough to not be put off by the light. Perhaps a config option that allows the user to specify mods or entities allowed to bypass?

I'm not sure if this is possible or something you're interested in adding, but a player suggested it to me and I thought I'd bring it up. Thank you for your time!

**Comment by Xalcon** [comment]
generally this isnt a bad idea, i might look into that. Internally i just fill a list with entities that the torch is able to block. I intended to add a blacklist/whitelist option to the config, which should suffice, I think.

**Comment by katubug** [comment]
Yes, that would be perfect! Thank you so much!

**Comment by Xalcon** [comment]
I've taken a look at infernal mobs and i dont think it is possible to handle this at the moment. The issue is the way infernal mobs does its spawning. I block the spawning attempts during the `CheckSpawn` phase since thats the only phase were i am able to determine if a spawn attempt is done by natural rules (like light levels) or by artificals means (like mob spawners). Infernal mobs actually modifies existing entities after the checkspawn checks succeeded. With other words: i dont know if the entity that is about to spawn is an actual infernal mob.

I'm still going to implement the whitelisting feature in the future, but it wont work with infernal mobs just due to the way the mod works.

**Comment by katubug** [comment]
Ah okay! Well thank you very much for looking into it! I appreciate all
your hard work.
